services:
  app:
    build: ./backend
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  api:
    image: nginx:alpine
    container_name: laravel_api
    ports:
      - "3000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "3001:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/web.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: calculadoraDados
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
